### ISSUE TITLE
Add hash header to the CRS-via-HTTP api

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk#1135]
#### Summary
Current CRS serialization implementation in HTTP requires users to use unsafe code. The way the serialization is done ought to be changed so that clients could use safe code when deserializing.

#### Possible solution design or implementation
Switch serialization method from `to_raw_var_bytes` to `to_var_bytes`.

#### Additional context
This change will also decrease the size of sent data by approximately 50%.

**Comment by herr-seppia** [comment]
Current code just read the CRS from the file (uncompressed form) since no PublicParameter instance is saved anywhere

Adding that functionality to the node is quite dangerous due to:
1) Need to deser/serialize at every request (this lead to open a vulnerability on the node)
2) If we want to avoid the first point, we should cache it in memory, and it's going to increase the memory footprint.

What could be useful would be to add the hash to the response, to perform a checksum. But you will still trust a node

**Comment by miloszm** [comment]
Changed the goal of this issue to adding hash header for CRS HTTP api - this will eliminate user's vulnerability to corrupted CRS.
