### ISSUE TITLE
consensus: Adjust config parameters of adaptive timeout

### ISSUE THREAD

**Issue by goshawk-3** [dusk-network/rusk#1245]
#### Summary

Recently  implemented `adaptive` timeout is currently based on basic logic. The items below  should be refined and adjusted for better efficiency.

Algorithms:
- Adjust round base timeout accordingly
- Increase step base timeout on timeout event

Configurations:
- Default values for step_base_timeout, round_base_timeout and max_step_timeout
- Multiplier for Validation/Ratification timeout. (see also https://github.com/dusk-network/rusk/pull/1230#discussion_r1444385586)

#### Relevant Context (optional)

See also: https://github.com/dusk-network/rusk/pull/1230#issue-2064161339

#### Possible Solution (optional)

https://github.com/dusk-network/rusk/issues/1170

**Comment by fed-franz** [comment]
After giving it some thought, this is my proposal:

INITIAL_BASE_TIMEOUT = 2
round_base_timeout = INITIAL_BASE_TIMEOUT

- at iteration N:
  - `iteration_base_timeout = round_base_timeout + N`
  - `proposal_timeout = iteration_base_timeout * 2`
  - `validation_timeout = iteration_base_timeout * 3`
  - `ratification_timeout = iteration_base_timeout * 3`
  
- at round R:
  - avg_validation_time = (sum of validation time of last 5 blocks divided by 5)
  - new base = round_up( avg_validation_time / 3)

Examples timeout values:

with round_base=2:
 - iteration 0: proposal=4 secs, validation/ratification=8 secs
 - iteration 1: proposal=6 secs, validation/ratification=9 secs
 - iteration 2: proposal=8 secs, validation/ratification=12 secs
 - ...
 - iteration 28: proposal=60 secs, validation/ratification=90 secs
 
When Proposal timeout reaches 60 seconds we stop increasing (if we consider this value as fixed, but we might also adjust MAX_STEP_TIMEOUT depending on the base timeout).
 

adjustment:
  - last 5 elapsed time of validation: 5, 4, 15, 10, 4 --> avg = 7.6 
  - round_base = round_up(7.6/3) = 3
  - next round, iteration 0: proposal_timeout = 6 seconds, validation/ratification = 9 seconds
  
Notes:
 - I decided to go for a linear increment between iterations, because it's simpler and spread the timeout increase over more iterations, which I think is better (especially considering that the base timeout should adjust to an optimal value over time).
 - In choosing the multipliers I mostly considered the number of messages to be received plus a bit a computation associated to Proposal and Validation for the VST. I kind of expect Validation to be the step taking the longer. 
 These values are by no means definitive and should be refined if necessary based on tests (for instance, I'm not sure Ratification requires as much time as Validation, nor if Validation actually takes longer than Proposal).
- For the round_base_timeout adjustment I decided to use the elapsed time exclusively, because basing the adjustment on iteration number / block label only does not allow to decrease the round_base_timeout. Since to allow it to be reduced we need to take into account some elapsed time, it made more sense to me to simply use it anyway.
- I preferred to take an average of the last 5 blocks (but it could be 10 as well) and not just the last block because this better deals with occasional variations in the network latency.

Let me know what do you think

**Comment by goshawk-3** [comment]
> In choosing the multipliers I mostly considered the number of messages to be received plus a bit a computation associated to Proposal and Validation for the VST. I kind of expect Validation to be the step taking the longer.

The number of messages is not always a fair indicator.  Both Validation and Ratification votes  are small fixed-sized messages while Proposal message could be extended up to MAX_BLOCK_SIZE thus propagating 43 votes might be faster than a complete broadcast of a Proposal msg.

>  I kind of expect Validation to be the step taking the longer.

Correct. The verification of both the candidate header (all certificate signatures) and candidate txn set (VST call) in the Validation step might be costly and is definitely the bottleneck of each iteration.

**Comment by fed-franz** [comment]
> The number of messages is not always a fair indicator. Both Validation and Ratification votes are small fixed-sized messages while Proposal message could be extended up to MAX_BLOCK_SIZE/ MAX_BLOCK_GAS thus propagating 43 votes might be faster than a complete broadcast of a Proposal msg.

Fair point. I think for each step we should consider the following:
- number of messages
- size of messages
- computation involved before broadcasting the message

In this respect:
- Proposal has:
  - 1 big-size message
  - needs to compute EST
- Validation:
  - up to 64 small-size messages  
  - needs to compute VST
- Ratification:
  - up to 64 small-size messages

So maybe, we should align Proposal and Validation timeouts and reduce Ratification. That is:
- `proposal_timeout = iteration_base_timeout * 3`
- `validation_timeout = iteration_base_timeout * 3`
- `ratification_timeout = iteration_base_timeout * 2`

What do you think?

@herr-seppia could you give us your opinion as well?

**Comment by goshawk-3** [comment]
> Proposal has:
    1 big-size message
    needs to compute EST

I don't want to mislead you. Proposal will not be always a big-size msg, if empty candidate is proposed. We should know what could the approximate MAX SIZE of a Proposal message if Block is full.  

> So maybe, we should align Proposal and Validation timeouts and reduce Ratification. That is:
    proposal_timeout = iteration_base_timeout * 3
    validation_timeout = iteration_base_timeout * 3
    ratification_timeout = iteration_base_timeout * 2

I'd rather stick with this proposal for now. We might need to collect some data to re-adjust this accordingly.

**Comment by fed-franz** [comment]
> I don't want to mislead you. Proposal will not be always a big-size msg, if empty candidate is proposed. We should know what could be the approximate MAX SIZE of a Proposal message if Block is full.

Since it's hard to predict the size of a block, it's better to allocate enough time for the worst case scenario.
IIUC, the only limit for a block is the gas limit, so we could approximate MAX_SIZE by considering the gas for a simple transfer (which I think will be the minimum gas spent by a single transaction)

> I'd rather stick with this proposal for now. Later on, we might need to collect some data to re-adjust this accordingly.

Agreed

**Comment by fed-franz** [comment]
>     * `proposal_timeout = iteration_base_timeout * 3`
>     * `validation_timeout = iteration_base_timeout * 3`
>     * `ratification_timeout = iteration_base_timeout * 2`

I updated my message with this version

**Comment by fed-franz** [comment]
@goshawk-3, I've updated the description to clarify each variable and what we consider as `avg_validation_time`.
Thanks for your inputs on that
