### ISSUE TITLE
Scanning for notes should be less expensive

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/rusk#14]
This is a very expensive operation. Maybe we add some more data on the wallet, like the position of the notes, so the wallet can send the position to rusk?

_Originally posted by @vlopes11 in https://github.com/dusk-network/rusk/pull/7_

**Comment by CPerezz** [comment]
Any inputs on this @julesdesmit ?  Sending the position is obviously not an option.

Can you update on that? It seems to be more related to kelvin and therefore, you should discuss it with @krl

**Comment by julesdesmit** [comment]
@CPerezz I think maybe @toghrulmaharramov may have had an idea on how to make it more efficient, but I'm not sure. I was kind of assuming the wallet will just save the indexes of any received tx and use that.

**Comment by toghrulmaharramov** [comment]
One approach would be to have a function scan the notes from index 0 until the latest known index. The wallet can encrypt and store the notes corresponding to the view key, as well as the index of the last scanned note. If the user logs into his/her wallet after a certain time, instead of scanning from index 0, we would pass the index of the last scanned note and scan the notes from that point onward.

**Comment by CPerezz** [comment]
We can annotate over the Notes and do multiple annotations to reduce the searches inside trees. 

So until we don't benchmark the final implementation, this can be closed.
