### ISSUE TITLE
Refresh Kadcast routing table more frequently

### ISSUE THREAD

**Issue by autholykos** [dusk-network/rusk#1488]
**Describe the bug**
For some VPS (e.g. Contabo, Vultr), we noticed that the firewall is not configurable to the extent we would like. Because of that, we have been noticing that nodes are lagging behind because they are connected to a low number of peers. In order to mitigate this problem, a temporary workaround might be to refresh the Kadcast peer table more often.

A consequence of this would be that nodes would lag behind the network tip (2-3 block behind), get slashed a lot, and struggling to catch up.

**To Reproduce**
Spawn a number of nodes on Contabo and see how they fare.

**Expected behaviour**
Nodes need to be connected to a high number of peers and not lag behind.

**Comment by autholykos** [comment]
We should also consider publishing a list of bootstrappers as there are a lot of people that lament the incapability of resolving our own bootstrapper URLs.

**Comment by jsepulveda** [comment]
for the ones that we got the tokens on wednesday could consider to extend the deadline set to March?. We couldn't get any uptime. And we need to have at least the 75%. I got the tokens on wednesday, on thursday I was able to synch and do the staking and since yesterday night I can't run the node since I'm in Contabo.

**Comment by autholykos** [comment]
Configuration is already updated in the ITN installer. No other action needed
