### ISSUE TITLE
Extend Bid function of Bid contract allows to extend long-time expired Bids

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/rusk#163]
The problem is quite simple. 

Nothing prevents a user to extend a `Bid` that was expired for example since `2*bid.expiration` blocks. This is weird since the specs of `extend_bid()` explicitly state that we only increase the `expiration` field of the `Bid` by `EXPIRATION_PERIOD (t_b in the specs)` and therefore, once this is done, the Bid of the user is still expired.

So the user spend Dusk on basically do nothing at all. Since the Bid stills being expired although it was extended.

We might want to prevent this situations to happen (I'm not sure) but I rise the issue so that it can be reviewed by @toghrulmaharramov

**Comment by CPerezz** [comment]
@toghrulmaharramov Any news? We want to deliver the Genesis Bundle in this iteration. And that includes the need of this logic defined.

**Comment by toghrulmaharramov** [comment]
@CPerezz forgot to fix it, sorry. The last assertion in Step 1 of Execution of extendBid() needs to assert that $\mathcal{B}.B^{h_{expiration}} > \sigma^h$ rather than what the specification currently asserts (the reverse to the statement above). I will fix the GitBook specification to have it in line with the implementation.

**Comment by toghrulmaharramov** [comment]
@CPerezz fixed and merged.

**Comment by CPerezz** [comment]
Thanks!! Unassigning you and just leaving me to impl it!
