### ISSUE TITLE
explorer: Extract "isDesktop" Utility for Consistent Client Width Check

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1747]
### Description:

On the Explorer, we currently use the condition `{#if clientWidth > 768}` multiple times across the app. To improve code maintainability and avoid repetitive hard-coded values, I suggest creating a utility function, such as `isDesktop`, that uses 768 as a constant. This will centralize the value and make future adjustments easier.

### Proposed Solution:

1. Create a utility function `isDesktop` that checks if `clientWidth` is greater than 768.
2. Replace all instances of `{#if clientWidth > 768}` with `isDesktop()`.

### Benefits:

- Improved code readability and maintainability.
- Easier updates to the threshold value in the future.
- Consistent use of the 768 constant across the application.

**Comment by deuch13** [comment]
I propose a different solution to this issue, instead of creating a function that depends on a constant we use the CSS `@media` selector and use 2 new classes that define the desktop/mobile breakpoints. These classes and the CSS rule will reside in the `main.css` file so that the whole application can have access to these classes. This way we do not create additional an function and constant and simply rely on CSS. The implementation can be seen in the attached PR.
