### ISSUE TITLE
consensus: Reduce the total number of iterations

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#1830]
#### Summary

Currently, we have 255 iterations for round. This is way too much for our needs and exacerbate the risk of forks in case of unfavorable network conditions.
We should reduce this number to a reasonable amount.

### Possible solution
Reduce `CONSENSUS_MAX_ITER` to `50` or lower

**Comment by autholykos** [comment]
Depends on #1234 
After the introduction of the emergency block, the number of iteration should be reduced to 32

**Comment by fed-franz** [comment]
> Depends on #1234 After the introduction of the emergency block, the number of iteration should be reduced to 32

Care to motivate the dependency and the number 32?

**Comment by autholykos** [comment]
After a discussion it was decided that: 
- the "relaxed" iterations should start at iteration 8.
- no attestation should be added after iteration 8, so not to make the block too bulky
- the emergency iterations would start at iteration 16. This because the probability to accept a block would increase as soon as we start to keep the iteration open
- maximum amount of iteration should be 64

The issue is related to #1234 but not strictly dependent on it
