### ISSUE TITLE
Explorer Fails to Load – Cannot Access Uninitialized Variable (Safari Only)

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1975]
### Description:
When using Safari, the Explorer fails to load due to an error related to accessing an uninitialized variable. This issue is specific to Safari and does not occur on other browsers.

<img width="2145" alt="Screenshot 2024-07-16 at 12 00 18" src="https://github.com/user-attachments/assets/8405c97a-1800-433c-a0e4-d8ecc14fc714">

### Update:
Seems the problem is caused by the asynchronous call in the `initialState` declaration (marketDataStore.js: 24). We need  to ensure that asynchronous code (such as the `await getStorage()`) is not used directly in an initialization context where it might not be fully resolved.

**Comment by ascartabelli** [comment]
Just an update: the issue is not caused by the top-level await per se, that Safari supports, but by a combination of factors that leads Safari into this (unresolved) bug: https://bugs.webkit.org/show_bug.cgi?id=242740.
Some of those factors are out of our control, so we devised a different implementation.
