### ISSUE TITLE
consensus: Disable re-propagation of future Quorums

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#2171]
#### Summary

As discussed prior and as detailed in [this advisory](https://github.com/dusk-network/rusk/security/advisories/GHSA-4h67-qvp4-8jg3), we need to fix a potential memory leak.

#### Solution

The advisory provides multiple pathways forward.

**Comment by autholykos** [comment]
This has been deprioritized in favor of #2247

**Comment by autholykos** [comment]
This is missing handling future Quorums by checking that the provisioners in the attestation signatures are eligible. This needs discussion.

**Comment by autholykos** [comment]
The whole Quorum propagation should be seen as an optimization, and quorum messages are somewhat lower priorities wrt candidate blocks and votes. Because of this, and due to the difficulty in verifying quorum messages related to future rounds, this issue simply pertains to disabling future quorum re-propagation.

**Comment by fed-franz** [comment]
Implemented by #2717
