### ISSUE TITLE
web-wallet: Remove network switching

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/rusk#2496]
We will publicly serve the explorer on three separate sub domains:

* devnet.apps.dusk.network/explorer
* testnet.apps.dusk.network/explorer
* apps.dusk.network/explorer

These for the 3 networks (devnet, testnet and mainnet).

1. Change the explorer so that it doesn’t use network requests for graphQL, because that will all be called on `/` 
2. Remove the network dropdown code.
3. We need a proxy on `apps.dusk.network/explorer` pointing  to a node (presumably on port 80?) (so this would be replacing the current component on DO with a proxy).  We also need this to work for `devnet.*` and `testnet.*` domains to point to explorers on those networks.
4. Configuration so that Rust bundles the explorer and that there can be env variable configuration for the node to serve the explorer or not.

**Comment by ZER0** [comment]
About the bundling, here some more details:

- "Apps Node" (node that serves web apps, including explorer) are a sub category of Archival Node. Meaning, a prover or provisioner won't be able to serve the explorer. That can be done via rust features flags (in the same way we have done until now for prover etc).

- For the time being we might just have one feature flag for the `explorer`, since it's the only one we actually need to bundle. Later we could improve this aspect.

- At compilation time, if such feature is enabled, the build script of rusk needs to build the apps (in this case, only the explorer), takes the result (the "dist"), zipping the content, and via `include_bytes`, the when the entry point (that could match the feature flag) is requested to the http server, it will get from the zipped file the resource requested from the client. The zip format is choosen because it's the one that keep the folder structure and can provided the requested resource without traverse the whole file. The archive is in memory and not unzipped anywhere, this is to prevent code injection.

> [!IMPORTANT]
> The `explorer` is therefore considered a sort of "administration tool", that is needed to inspect the current state of the node is served from. That also means, is considered as a desktop app, and if any update needs to be done, it will requires downloading a new version of the "Apps Node". We can implement later on a mechanism for self-upgrading with signed apps package, so the we will be able to release new version of the apps without necessary requiring new release of the binary.

**Comment by kieranhall** [comment]
For now, the approach in the app is to construct the API URL on `localhost` unless an environment variable `VITE_DEFAULT_NETWORK`  is passed, in which case one of the proxy URLs is used.
