### ISSUE TITLE
rusk-wallet: Add  ``context`` to errors 

### ISSUE THREAD

**Issue by sophielouisefeith** [dusk-network/rusk#2510]
#### Summary
> 💡 By Providing the user with more  specific ``error context``,  the reason why the program fails will be  more understandable for the non(technical) user(s)
Additionally it would help finding bugs more efficiently 

#### Possible solution design or implementation
> 💡 We've considered  the following two options
• Gathering information of the error in the main however this is not possible. 
• Using ``backtrace `` this would be to technical to the user.
The best possible solution will be  
implementing  ``anyhow::context`` to  all errors which are not manually implemented (e.g. wrapped errors such as IO etc). 

#### Additional context
> 💡 This issue is related to https://github.com/dusk-network/wallet-cli/issues/87

**Comment by Daksh14** [comment]
We don't need to add more context to the errors we just need to have better error reporting, anyhow is used in the binary to streamline error management but it shouldn't be used because we already have an error type in the library we should throw errors individually. I will close this issue, if there's problem in error handling in the wallet then an issue should be created for that
