### ISSUE TITLE
Restore flow: allow `enter` to insert the first word in the list when multiple matches are available

### ISSUE THREAD

**Issue by ascartabelli** [dusk-network/rusk#2879]
#### Summary

In the restore flow it can happen to have multiple entries matching the word you are typing (e.g. "fit" matching "fit" and "fitness".
By pressing enter we should insert the first word in the list (currently pressing enter does nothing in case of multiple matches).

**Comment by nortonandreev** [comment]
Hmm. Yeah, this is an edge case we have not considered. However, I am not too sure I would like for us to modify the behavior. If there is only one word available, and the user presses enter, the intention is clear. However, if we have fit and fitness, and the user presses enter by mistake, fit would be selected, whereas fitness might have been the right choice, which somewhat extends the possibility of error.

What I would do instead is, fix the tab order, so that the suggestion buttons are accessible on tab press.

**Comment by ascartabelli** [comment]
> What I would do instead is, fix the tab order, so that the suggestion buttons are accessible on tab press (and then tab -> enter should work).

Let's hear from @fed-franz as this was his suggestion.

**Comment by fed-franz** [comment]
I would prioritize quick insertion. If I typed my word I'd like Enter to insert it, like it does in other cases. A change in the pattern, just because of multiple potential matches, would be confusing imho.

Tab selection could be an option to quickly select the other words. But the first match should be automatically selected.

**Comment by fed-franz** [comment]
I would prioritize quick insertion. If I typed my word I'd like Enter to insert it, like it does in other cases. A change in the pattern, just because of multiple potential matches, would be confusing imho.

Tab selection could be an option to quickly select the other words. But the first match should be automatically selected.

**Comment by ascartabelli** [comment]
> I would prioritize quick insertion. If I typed my word I'd like Enter to insert it, like it does in other cases. A change in the pattern, just because of multiple potential matches, would be confusing imho.
> 
> Tab selection could be an option to quickly select the other words. But the first match should be automatically selected.

I do agree with you, for the record.

**Comment by nortonandreev** [comment]
I can pick this one up now.
