### ISSUE TITLE
web-wallet: Balance doesn't get updated after a transfer

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#2921]
Also applicable for Shielding / Unshielding – seems like logging out and in again, and another sync is needed.

**Comment by ascartabelli** [comment]
You need to wait for the transaction to be removed from the mempool for the balance to be updated: until then you have actually spent nothing.

**Comment by nortonandreev** [comment]
> You need to wait for the transaction to be removed from the mempool for the balance to be updated: until then you have actually spent nothing.

Makes sense. I guess we should find a way to communicate this to the user?

**Comment by ascartabelli** [comment]
> Makes sense. I guess we should find a way to communicate this to the user?

I briefly discussed about such a feature with @ZER0, along the lines of having detail about some of your balance being "on hold".
We'll think about it.

In the meantime maybe we can rephrase the "transaction completed" into something more meaningful.

That is, if the balance is actually updating in your experience: I never had a problem about it.
So first thing keep an eye about it and see if this bug is valid or not; then we can discuss about improving the UX.

**Comment by ascartabelli** [comment]
Side note: first step about improving the UX should be tackling https://github.com/dusk-network/rusk/issues/2877

**Comment by nortonandreev** [comment]
> > Makes sense. I guess we should find a way to communicate this to the user?
> 
> 
> 
> I briefly discussed about such a feature with @ZER0, along the lines of having detail about some of your balance being "on hold".
> 
> We'll think about it.
> 
> 
> 
> In the meantime maybe we can rephrase the "transaction completed" into something more meaningful.
> 
> 
> 
> That is, if the balance is actually updating in your experience: I never had a problem about it.
> 
> So first thing keep an eye about it and see if this bug is valid or not; then we can discuss about improving the UX.
> 
> 

Was about to say, we have info copy on the transaction complete state so we can use that as a starting point to provide more details so as to set the expectations.

**Comment by ascartabelli** [comment]
Closing as there is no bug.
