### ISSUE TITLE
Webwallet version 0.7.0 not loading on IPad (safari and chrome)

### ISSUE THREAD

**Issue by Rikkie82** [dusk-network/rusk#2931]
**Describe the bug**
on two iPads (one never visited dusk website/apps before), webwallet won’t load properly.

**To Reproduce**
Go to url and try to open webwallet.

**Expected behaviour**
Opens like on iPhone or laptop and you can unlock wallet to transact.

**Logs/Screenshot**
![05F3242A-1909-4463-9773-D141C0694DB3](https://github.com/user-attachments/assets/b9575965-59c4-454e-9648-b91c410b8659)
![59FAA043-ED74-4325-BB03-61A6AAFFFE7D](https://github.com/user-attachments/assets/799719d3-6766-4523-a00f-4501e7c29579)

**Platform**
Fill as appropriate
 
 - OS: iPadOS 16.1.1
 - Browser chrome & safari

**Additional context**
restart of iPad did not solve it.

**Comment by Fulviuus** [comment]
Works fine on iPad pro 11 (M4) with iPad OS 18.1 and Safari

**Comment by nortonandreev** [comment]
Thank you for reporting this issue with Webwallet 0.7.0 on iPadOS 16.1.1. Here’s some context that may help explain the problem.

As of iPadOS 16.1.1, third-party browsers (like Chrome) are restricted to using the WebKit engine provided by the OS, meaning they are limited to a specific WebKit version until the OS is updated. This restriction can limit access to newer web technologies available in the latest WebKit versions. Although Apple has recently announced changes in iOS 17.4 (currently applicable in the EU only) allowing alternative browser engines, devices running iPadOS 16.1.1 still rely on the older OS-provided WebKit engine.

To investigate further, I tested the app on an iOS 16 simulator and observed that the production URL does cause a crash, though the error message isn’t very informative. However, when running a local build on localhost, everything works as expected. This is a bit of an unfortunate situation, as it makes debugging a little harder. But also means that, perhaps, the issue is not that major and ensuring browser compatibility with the older version might be feasible.

Given that our primary focus is on supporting the most recent browsers, this issue will be given lower priority. Nonetheless, we’ll keep it open and continue investigating. Thank you for your patience, and we’ll keep you updated on any progress.

**Comment by Rikkie82** [comment]
Upgraded IOS version to 17.7.1 and issue is resolved indeed.
