### ISSUE TITLE
Feature Request: Add Build CI Workflow for Prover and Archiver Binaries

### ISSUE THREAD

**Issue by lufa23** [dusk-network/rusk#3258]
# Description
Currently, the documentation outlines how to build a prover or archiver manually, which is helpful. However, to enhance usability and reduce friction for users, it would be beneficial to set up a build CI workflow that automates this process. This workflow could be similar to the one used for the Rusk wallet, generating all required binary permutations.

# Proposal
Set up a CI workflow:

- Create a CI pipeline that builds the prover and archiver binaries.
- Generate binaries for all necessary permutations (e.g., platform-specific variations).
- Ensure the workflow outputs downloadable binaries, making them accessible directly through GitHub releases or similar platforms.
- Integrate the workflow into the existing CI/CD pipeline.
- Test the output to ensure binaries are correctly generated and functional.

**Comment by HDauven** [comment]
@lufa23 this CI workflow already creates an archiver binary for 3 different targets: https://github.com/dusk-network/rusk/blob/master/.github/workflows/rusk_build.yml

The prover is already inclusive with the default, but we can also add a separate one. One reason I'm hesitant at the moment to do the prover separately is because of the long build times for the current workflow. 

I outlined a CI workflow that's more flexible and lets you target more specific combinations here: https://github.com/dusk-network/rusk/pull/3231

Waiting for @pmoranga to clean it up.

**Comment by HDauven** [comment]
Resolved by #3231
