### ISSUE TITLE
Tracking issue for benchmarks

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#363]
This issue tracks progress on performance measurements.

In the context of the Wasmer migration [here](https://github.com/dusk-network/rusk-vm/pull/249), and the Rkyv migration [here](https://github.com/dusk-network/microkelvin/pull/79), which both eventually impact performance measurements, it seemed like a good thing to track the impact that these changes will have on contract call performance.

This is also a place to discuss the current benchmarks and how accurate they are to what we want to measure. The performance benches were introduced in #362.

**Comment by vlopes11** [comment]
We need to isolate the ZK overhead from the VM benchmarks.

The ZK part is known to be dependent on the number of constraints of the circuit, for both proving and verification. That by itself isolates the question from the VM benchmarks since the VM isn't aware of the constraints count.

Having that said, the measurement must change to take only `transact` and `query` as measured parts.

If we find bottlenecks, it could be worthy to also add some flamegraphs
