### ISSUE TITLE
Implement rusk-vm config file functionality and rusk-vm config usage

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk#375]
**Describe what you want implemented** 
Rusk-vm config file should be managed by Rusk and used for Rusk-vm configuration when interacting with Rusk-vm.

**Describe "Why" this is needed**
Rusk needs a way to configure vm settings, mainly instrumentation.

**Describe alternatives you've considered**
Rusk-vm could hold a configuration file but this is wrong as rusk-vm is a library, while Rusk is a server using rusk-vm,
so it should control configuration.

**Additional context**
Related work will be to elevate rusk-vm to native wasmer instrumentation - once this is done, rusk-vm configuration
will likely have to change.

**Comment by ZER0** [comment]
Let's figure out after piecrust porting.

**Comment by HDauven** [comment]
@ureeves @ZER0 @miloszm is this still relevant?

**Comment by HDauven** [comment]
Closing this since it is not relevant for now. 

In the situation where we configure certain options, it is better if they're hardcoded and not changeable by node runners, which could lead to situations where their nodes do not agree with the majority.

If we were to decide to use configurations for upgrades, this would lead to multiple configuration files per upgrade, which is not ideal.
