### ISSUE TITLE
Plonk operations in Fr

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/rusk#405]
# Schnorr signature

let s be in $\mathbb{F}_r$ (secret key)
let e be in $\mathbb{F}_r$ (entropy)
let m be in $\mathbb{F}_q$ (message)
let H be a hash that maps to $\mathbb{F}_q$
let H' be a hash that maps to $\mathbb{F}_r$

let G be a generator of jubjub
let G' be another generator of jubjub

# Sign

R := e · G
R':= e · G'

c := H'(R || R' || m)
u := e - c · s

# Verify

K := s · G
K':= s · G'

P := u · G + c · K
Q := u · G'+ c · K'

# Proof

R == P
e · G == (e - c · s) · G + c · s · G
e · G == (e - c · s + c · s) · G
e == e

R'== Q
e · G'== (e - c · s) · G'+ c · s · G'
e · G'== (e - c · s + c · s) · G'
e == e

# Problem

u is performed in $\mathbb{F}_r$, but plonk can only perform addition and multiplication of scalars in $\mathbb{F}_q$.

let (x, y, w, z) be in $\mathbb{F}_q$
let f be a function that truncates $\mathbb{F}_q$ to $\mathbb{F}_r$

f(x) == u
f(y) == e
f(w) == c
f(z) == s

However, the following will not hold because the operations that would overflow $\mathbb{F}_r$ won't overflow $\mathbb{F}_q$

x := y - w · z

x != u

---

# Different types of elements

- BLS points have coordinates in $\mathbb{F}_p$
- BLS has order $q$ $\rightarrow$ BLS scalars are in $\mathbb{F}_q$
- Jubjub points have coordinates in $\mathbb{F}_q$
- Any element of a circuit is in $\mathbb{F}_q$
- Jubjub has order $r$ $\rightarrow$ Jubjub scalars are in $\mathbb{F}_r$

* BLS to make proofs
BLS points (x,y), where x and y live in some $\mathbb{F}_p$.
* We use the order of BLS to make circuits
BLS has order $q$, so we use "BLS scalars", which are elements that live in $\mathbb{F}_q$.
* We have Jubjub to implement elliptic curve crypto inside a circuit
Jubjub points (x,y) have coordinates x and y that live in $\mathbb{F}_q$ (they are BLS scalars).
* Jubjub "has order" $r$
Jubjub has order $r$, so if we use "Jubjub scalars", they live in $\mathbb{F}_r$.

**Jubjub**
- Addition of points
$$ (x_1,y_1) + (x_2, y_2)$$
Then $x_1, y_1, x_2, y_2$ are BLS scalars.
- Scalar multiplied by a point
$$ s * P = s * (x,y) $$
Then $s$ is a Jubjub scalar (in $\mathbb{F}_r$) and $x$ and $y$ are BLS scalars. And the resulting point will also have BLS scalars as coordinates.

**Comment by javiersilva0** [comment]
This assumes that it is the proving (signing) algorithm of Schnorr that is implemented in the circuit. This would involve computing $$u= e - cs$$, which means performing arithmetic in $$\mathbb{F}_r$$. This clashes with the fact that the circuit deals with $$\mathbb{F}_q$$-arithmetic. This would entail dealing with non-native arithmetic, with a $$O(\log q)$$ efficiency blowup. 

However, the current version implements the Schnorr verification algorithm in-circuit, not the proving algorithm. The verification algorithm does not incur into non-native arithmetic, so this problem is avoided.
