### ISSUE TITLE
The stake contract uses the block height for the signature message

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#566]
**Describe the bug**
The stake contract currently uses a message for the signature that fixes the `block_height` at which the contract gets called. This ensures that a transaction generated during the block prior can never pass through the contract successfully. Given the time it takes to generate a proof this is almost sure to be the case. Furthermore, there is currently no way to have Rusk pass the block height to the wallet, since only `dusk-blockchain` has knowledge of it.

**To Reproduce**
https://github.com/dusk-network/rusk/blob/f489713408954d4e201d4622bc588b521275b00f/contracts/stake/src/contract.rs#L86-L93

**Expected behaviour**
A stake transaction created the block prior should still pass the contract successfully. 

**Logs/Screenshot**
N/A

**Platform**
N/A

**Additional context**
This is the end of a rabbit hole of issues that first started with #560, and culminated in [#46](https://github.com/dusk-network/wallet-core/issues/46), which is currently blocked by the result of this issue

**Comment by vlopes11** [comment]
`block_height` shouldn't necessarily be the current one. Instead, we could add `eligibility` argument to contract `stake` method and validate it in https://github.com/dusk-network/rusk/blob/f489713408954d4e201d4622bc588b521275b00f/contracts/stake/src/wasm.rs#L36 instead of taking the current block height.

The `eligibility` as part of the signature is mandatory to prevent non-owners of the stake to mutate its state.
