### ISSUE TITLE
Two prover calls result in OoM in infra

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#715]
**Describe the bug**
Two concurrent calls to the prover service will result in OoM, given the current configuration of our infrastructure.

**To Reproduce**
Make two simultaneous calls to a prover in a memory constrained environment - say 2 GB.

**Expected behaviour**
The expectation is for calls to take longer to process instead of resulting in an OoM.

**Logs/Screenshot**
N/A

**Platform**
N/A

**Additional context**
https://github.com/dusk-network/dusk-deployer/issues/34

**Comment by vlopes11** [comment]
I came to some conclusions after experimenting with [a parallelization script](https://gist.github.com/vlopes11/96c65c7221868563bc0f06ba28b917ba)

- A prover will consume ~800M per thread
- A static ~2G will be allocated for the CRS and the keys. Note that the SRS domain won't impact too much on that since it is of a different magnitude order

Hence, the minimum memory for a prover is 4G, and recommended is 8G (also to allow the OS to have its own allocations)

**Comment by herr-seppia** [comment]
Closing because this is an infrastructural issue solved with the scaling mechanism mentioned in the referencing issue
