### ISSUE TITLE
Remove delay in generate_block

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#913]
#### Summary
Currently, `generate_block` waits `CONSENSUS_DELAY_MS` to avoid avoid consensus-split situation.
This should not be needed anymore because we include `iteration` in the block header.

**Comment by goshawk-3** [comment]
@fed-franz Could you elaborate a bit more why you think that adding iteration number in block header resolves the data-race (consensus-split) between two different iterations?

**Comment by goshawk-3** [comment]
> This because we should have a target block time (~10sec?) and not spawning block at every sec

That's correct. We decided to add a delay in generate_candidate_block in order to maintain target block time of 10s when a block is empty.

Additionally, there used to be a delay in reduction step (prior to VST call) that aims at mitigating consensus split (https://github.com/dusk-network/rusk/issues/950). 

> Previous implementation without the iteration in the header, allow a single provisioner to generate multiple block at different iteration having the same hash (since they were built at the same instant).
Even if the step was present into the reduction messages, the voted hash was the same. Right?

Agreed. Adding iteration makes sense. However, IMO the change  neither  resolves nor mitigates  `consensus split`.

**Comment by fed-franz** [comment]
Just to add some context, this issue was opened following @herr-seppia's indication. 
So if he says not to remove it, I have nothing to add :). 
Closing this issue for now.
